os: Visual Studio 2015
configuration:
  - Debug
  - Release

build:
  verbosity: normal

before_build:
  - cmake . -DSAL_UNITTESTS=yes -G "Visual Studio 14 2015 Win64"

build_script:
  - type sal/config.hpp
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ps: scripts\appveyor_test_script.ps1 -Config %CONFIGURATION% -Output unittests.xml

on_finish:
  - ps: (New-Object "Net.WebClient").UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
