version: 0.3.0.{build}

branches:
  except:
    - gh-pages

image: Visual Studio 2015

configuration:
  - Debug
  - Release

before_build: |
  'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat' x64 10.0.10240.0
  cmake . -DSAL_UNITTESTS=yes -G "Visual Studio 14 2015 Win64"

build_script: |
  cmake --build . --config %CONFIGURATION%

test_script: |
  ps: scripts\appveyor_test_script.ps1 -Config %CONFIGURATION% -Output unittests.xml

on_finish: |
  ps: (New-Object "Net.WebClient").UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unittests.xml))
