language: cpp

os:
  - linux
  - osx

osx_image: xcode7.3

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug TEST_TARGET=test
  - BUILD_TYPE=Release TEST_TARGET=test

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Coverage TEST_TARGET=gen-cov

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - kubuntu-backports
    packages:
      - g++-6
      - clang-3.8
      - cmake

install:
  - source scripts/travis_install.sh

script:
  - source scripts/travis_script.sh

after_success:
  - source scripts/travis_success.sh
