language: cpp

os:
  - linux
  - osx

osx_image: xcode7.3

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug TEST_TARGET=test
  - BUILD_TYPE=Release TEST_TARGET=test

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Coverage TEST_TARGET=gen-cov

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
      - kubuntu-backports
    packages:
      - g++-6
      - clang-3.9
      - cmake

install:
  - source scripts/travis_install-${TRAVIS_OS_NAME}-${CC}.sh

script:
  - cmake . -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build .
  - cmake --build . --target ${TEST_TARGET} -- ARGS=--output-on-failure

after_success:
  - test "${BUILD_TYPE}" = "Coverage" && source scripts/travis_success-codecov.sh || true
